

<head>

    <meta charset="utf-8" />

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width" />

    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>

    <title>Welcome to Taxi Booking</title>

    <link rel="STYLESHEET" type="text/css" href="stylesheets/fg_membersite.css" />

    <!-- Included CSS Files -->
    <link rel="stylesheet" href="stylesheets/foundation.css">
   
    <!--<link rel="stylesheet" href="stylesheets/left-menu.css">-->

    <link rel="stylesheet" href="stylesheets/app.css">

    <link rel="STYLESHEET" type="text/css" href="stylesheets/pwdwidget.css" />

    <script type='text/javascript' src='javascripts/gen_validatorv31.js'></script>

    <script src="javascripts/pwdwidget.js" type="text/javascript"></script>      

    <script src="javascripts/modernizr.foundation.js"></script>

    <!--[if lt IE 9]>
        <link rel="stylesheet" href="stylesheets/ie.css">
    <![endif]-->


    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
     <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->   


</head>